import { parseHTML } from 'linkedom';
import { zipSync, strToU8 } from 'fflate';
import { minify } from 'html-minifier-terser';

function flattenNode(el, renames) {
  for (const child of [...el.children]) flattenNode(child, renames);
  const isWrapper = el.tagName === 'DIV' && el.children.length === 1 &&!el.id &&!el.textContent.trim();
  if (isWrapper) {
    const child = el.children[0];
    if (el.hasAttribute('style')) {
      const s = child.getAttribute('style');
      child.setAttribute('style', s? `${s};${el.getAttribute('style')}` : el.getAttribute('style'));
    }
    el.replaceWith(child); el = child;
  }
  const oldKey = el.id || [...el.classList].find(c => renames[c]);
  const newName = renames[oldKey];
  if (newName) { el.removeAttribute('class'); el.id = newName; }
}

async function inlineImages(document) {
  const svgs = [...document.querySelectorAll('img[src^="data:image/svg+xml"], img[src$=".svg"]')];
  for (const img of svgs) {
    try {
      const url = img.src;
      if (url.startsWith('http')) {
        const svgText = await fetch(url).then(r => r.text());
        img.outerHTML = svgText; // replace <img> with inline <svg>
      }
    } catch (e) {}
  }
}

function dedupeFonts(document) {
  const usedFonts = new Set();
  document.querySelectorAll('[style*="font-family"]').forEach(el => {
    const match = el.style.fontFamily.match(/['"]?([^'"]+)['"]?/);
    if (match) usedFonts.add(match[1]);
  });
  document.querySelectorAll('style').forEach(styleTag => {
    styleTag.textContent = styleTag.textContent.replace(/@font-face\s*{[^}]*font-family:\s*['"]?([^'"]+)['"]?[^}]*}/g, (match, font) => {
      return usedFonts.has(font)? match : '';
    });
  });
}

export async function onRequestPost({ request }) {
  const fd = await request.formData();
  const file = fd.get('file');
  const renames = JSON.parse(fd.get('renames') || '{}');
  const splitMode = fd.get('splitMode') || 'zip';
  const htmlText = await file.text();
  const { document } = parseHTML(htmlText);
  const originalSize = htmlText.length;

  flattenNode(document.body, renames);
  await inlineImages(document); // 1. Image inlining
  dedupeFonts(document); // 2. Font dedupe

  // Extract CSS + GSAP
  let css = `*{box-sizing:border-box;margin:0}body{font-family:system-ui}`;
  let gsap = [`import{gsap}from"gsap";import{ScrollTrigger}from"gsap/ScrollTrigger";gsap.registerPlugin(ScrollTrigger);`];
  document.querySelectorAll('[style*="transform"],[style*="opacity"]').forEach(el => {
    if (!el.id) el.id = `a${Math.random().toString(36).slice(2,8)}`;
    const style = el.getAttribute('style'); el.removeAttribute('style');
    const anim = style.match(/transform:[^;]+|opacity:[^;]+/g)?.join(',').replace(/;/g,',');
    if (anim) {
      css += `#${el.id}{${style.replace(/transform:[^;]+;?|opacity:[^;]+;?/g,'')}}`;
      gsap.push(`gsap.from("#${el.id}",{${anim},duration:.6,scrollTrigger:"#${el.id}"});`);
    }
  });

  let finalHtml = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${document.title}</title><link rel="stylesheet" href="style.css"></head><body>${document.body.innerHTML}<script src="https://unpkg.com/gsap@3/dist/gsap.min.js"></script><script src="https://unpkg.com/gsap@3/dist/ScrollTrigger.min.js"></script><script type="module" src="animate.js"></script></body></html>`;

  // 3. Minify everything
  finalHtml = await minify(finalHtml, { collapseWhitespace: true, removeComments: true, minifyCSS: true, minifyJS: true });
  css = await minify(`<style>${css}</style>`, { minifyCSS: true }).then(r => r.replace(/^<style>|<\/style>$/g,''));
  const jsCode = await minify(gsap.join('\n'), { minifyJS: true });

  if (splitMode === 'inline') {
    const inlined = finalHtml.replace('<link rel="stylesheet" href="style.css">', `<style>${css}</style>`).replace('<script type="module" src="animate.js"></script>', `<script type="module">${jsCode}</script>`);
    return new Response(inlined, { headers: { 'Content-Type': 'text/html', 'X-Size-Reduction': `${((1-inlined.length/originalSize)*100).toFixed(1)}%` }});
  }

  const zip = zipSync({
    'index.html': strToU8(finalHtml),
    'style.css': strToU8(css),
    'animate.js': strToU8(jsCode),
    'README.txt': strToU8('Generated by Framer Flatten\nRun: npx serve\n')
  });
  return new Response(zip, { headers: { 'Content-Type': 'application/zip', 'Content-Disposition': 'attachment; filename="site.zip"', 'X-Size-Reduction': `${((1-(finalHtml.length+css.length+jsCode.length)/originalSize)*100).toFixed(1)}%` }});
}
